apiVersion: v1
kind: Pod
metadata:
  name: fio-tester-kkdp2
spec:
  nodeSelector:
    kubernetes.io/hostname: ocpnp-zdpgh-worker-0-jg9cz
  containers:
  - name: fio-tester-kkdp2
    image: quay.io/openshift-scale/scale-ci-fio
